# Generated by Django 5.2 on 2025-04-29 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_category_slug_alter_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework/files/'),
        ),
    ]
