# Generated by Django 5.2 on 2025-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_homework_created_at_alter_homework_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('ready', 'Ready')], default='uploading'),
        ),
    ]
